"""
===========================================================================
Adaptive Mixture of Experts (A-MoE)
Weighted Fusion Layer

Author : Badrinath & Abdul Azim

Description
-----------
Combines expert probability predictions using the adaptive weights
generated by the Gating Network.

Mathematical Formulation
------------------------
Final Prediction

        n
P = Σ (Wi × Ei)
       i=1

where

Wi = Weight assigned by Gating Network
Ei = Expert probability prediction

=========================================================================== 
"""

from typing import Tuple

import torch
import torch.nn as nn


class WeightedFusion(nn.Module):
    """
    Adaptive weighted fusion layer.

    Inputs
    ------
    expert_predictions

        Shape

        (batch_size, n_experts)

    expert_weights

        Shape

        (batch_size, n_experts)

    Output
    ------
    Final churn probability

        Shape

        (batch_size,)
    """

    def __init__(self) -> None:

        super().__init__()

    # ------------------------------------------------------------------ #

    def forward(
        self,
        expert_predictions: torch.Tensor,
        expert_weights: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute weighted expert prediction.

        Parameters
        ----------
        expert_predictions

            Expert probability matrix

        expert_weights

            Adaptive weights from Gating Network

        Returns
        -------
        torch.Tensor

            Final probability
        """

        final_prediction = torch.sum(
            expert_predictions * expert_weights,
            dim=1,
        )

        return final_prediction

    # ------------------------------------------------------------------ #

    @staticmethod
    def normalize_weights(
        weights: torch.Tensor,
    ) -> torch.Tensor:
        """
        Normalize weights.

        Mostly used during debugging.

        Returns
        -------
        torch.Tensor
        """

        return weights / weights.sum(
            dim=1,
            keepdim=True,
        )

    # ------------------------------------------------------------------ #

    @staticmethod
    def weighted_predictions(
        expert_predictions: torch.Tensor,
        expert_weights: torch.Tensor,
    ) -> torch.Tensor:
        """
        Return weighted prediction matrix.

        Useful for visualization.

        Returns
        -------
        torch.Tensor

        Shape

        (batch_size, n_experts)
        """

        return expert_predictions * expert_weights

    # ------------------------------------------------------------------ #

    @staticmethod
    def explain_prediction(
        expert_predictions: torch.Tensor,
        expert_weights: torch.Tensor,
    ) -> Tuple[
        torch.Tensor,
        torch.Tensor,
        torch.Tensor,
    ]:
        """
        Explain prediction.

        Returns

        Expert Predictions

        Expert Weights

        Weighted Contributions
        """

        contribution = (
            expert_predictions
            * expert_weights
        )

        return (
            expert_predictions,
            expert_weights,
            contribution,
        )

    # ------------------------------------------------------------------ #

    def __repr__(self):

        return (
            "WeightedFusion("
            "Adaptive Expert Fusion)"
        )